#! /bin/bash

if [ ! -d "build_${HOSTNAME}" ]; then
        mkdir "build_${HOSTNAME}"
fi
cd "build_${HOSTNAME}" && \
cmake -C ../user_desktop.cmake \
-DCMAKE_CXX_FLAGS="-std=c++11" \
.. && make && cd .. && \
if [ ! -e start_demo_cave ] ; then
#	echo "#! /bin/bash " > start_demo
#	echo "./build/main -f config/lrz_cave_vrpn.csm" >> start_demo
	chmod +x start_*
fi
