
#pragma once

#include <string>

static std::string _vertex_shader =
"#extension GL_ARB_gpu_shader5 : enable\n"
"varying vec3 ViewDirection;\n"
"varying vec3 ObjectPosition;\n"
"varying vec3 Normal;\n"
"varying vec2 TexCoord;\n"
"uniform mat4 ViewMatrix;\n"
"void main(void)\n"
"{\n"
"	TexCoord       = vec2(gl_MultiTexCoord0);\n"
"   ObjectPosition = vec3(gl_ModelViewMatrix * gl_Vertex);\n"
"   ViewDirection  = - ObjectPosition.xyz;\n"
"   Normal         = gl_NormalMatrix * gl_Normal;\n"
"	vec4 displacedPosition = inverse(ViewMatrix) * gl_ModelViewMatrix * gl_Vertex;\n"
"   displacedPosition += vec4(0, -0.00003 * (displacedPosition.z*displacedPosition.z), 0, 0);\n"
"   gl_Position    = gl_ProjectionMatrix * ViewMatrix *displacedPosition;\n"
"   gl_FrontColor  = gl_FrontMaterial.diffuse;\n"
"}\n"
"\n";

static std::string _water_vertex_shader =
"#extension GL_ARB_gpu_shader5 : enable\n"
"varying vec3 ViewDirection;\n"
"varying vec3 ObjectPosition;\n"
"varying vec3 Normal;\n"
"varying vec2 TexCoord;\n"
"uniform float elapsedTime;\n"
"uniform mat4 ViewMatrix;\n"
"uniform float SpeedFactor;\n"
"void main(void)\n"
"{\n"
"	TexCoord = vec2(gl_MultiTexCoord0);\n"
"   ObjectPosition = vec3(gl_ModelViewMatrix * gl_Vertex);\n"
"   ViewDirection  = - ObjectPosition.xyz;\n"
"   Normal         = gl_NormalMatrix * gl_Normal;\n"
"	vec4 displacedPosition = inverse(ViewMatrix) * gl_ModelViewMatrix * gl_Vertex;\n"
"   displacedPosition += vec4(0, -0.00003 * (displacedPosition.z*displacedPosition.z) + 10 * sin((displacedPosition.z / SpeedFactor + displacedPosition.x)/7), 0, 0);\n"
"   gl_Position    = gl_ProjectionMatrix * ViewMatrix *displacedPosition;\n"
"   gl_FrontColor  = gl_FrontMaterial.diffuse;\n"
"}\n"
"\n";

static std::string _fragment_shader =
"float SpecularPower = 1.0;\n"
"\n"
"uniform sampler2D baseMap;\n"
"uniform int useTexture;\n"
"\n"
"varying vec2 TexCoord;\n"
"varying vec3 ViewDirection;\n"
"varying vec3 ObjectPosition;\n"
"varying vec3 Normal;\n"
"\n"
"void main( void )\n"
"{\n"
"   vec3  LightDirection = normalize( gl_LightSource[0].position.xyz);\n"
"   vec3  Normal         = normalize( Normal );\n"
"   float NDotL           = dot( Normal, LightDirection ); \n"
"   \n"
"   vec3  Reflection     = normalize( ( ( 2.0 * Normal ) * NDotL ) - LightDirection ); \n"
"   vec3  ViewDirection  = normalize( ViewDirection );\n"
"   float RDotV           = max( 0.0, dot( Reflection, ViewDirection ) );\n"
"   \n"
"   vec4  BaseColor      = texture2D(baseMap, TexCoord);\n"
"   \n"
"   vec4  TotalAmbient   = gl_LightSource[0].ambient * BaseColor; \n"
"   vec4  TotalDiffuse   = gl_LightSource[0].diffuse * NDotL * BaseColor; \n"
"   vec4  TotalSpecular  = gl_LightSource[0].specular * ( pow( RDotV, SpecularPower ) );\n"
"   \n"
"   gl_FragColor = ( TotalAmbient + TotalDiffuse + TotalSpecular );\n"
"}\n";